baseURL = "https://boerman.dev/"
languageCode = "en-us"
title = "Blog Frank Boerman"
theme = "terminal"
paginate = 5


[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  [languages]
  [languages.en]
    title = "FBoerman Blog"
    subtitle = "Een verzameling aan gedachten"
    keywords = ""
    copyright = "Frank Boerman 2019"
    menuMore = "Lees verder"
    readMore = "Lees verder"
    readOtherPosts = "Lees andere posts"

    [languages.en.params.logo]
      logoText = "FBoerman"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "0. Posts"
        name = "0. Posts"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "1. About"
        name = "1. Over Mij"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "2. Contact"
        name = "2. Contact"
        url = "/contact"
